# Generated by Django 5.1.7 on 2025-03-27 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rating', models.CharField(choices=[('R1', '1 Yulduz'), ('R2', '2 Yulduz'), ('R3', '3 Yulduz'), ('R4', '4 Yulduz'), ('R5', '5 Yulduz')], default='R5', max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_dishes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
